version: "3.8"

services:
  ckan:
    # Do not set the container_name property
    # update_ckan_container.sh script requires Docker to set the container name dynamically
    # container_name: ckan 
    build:
      context: ckan/
      dockerfile: Dockerfile
      args:
        - TZ=${TZ}
        - SUBAK_EXT_GIT_BRANCH=${SUBAK_EXT_GIT_BRANCH:-main}
    env_file:
      - .env
    links:
      - db
      - solr
      - redis
    volumes:
      - ckan_storage:/var/lib/ckan

  caddy:
    container_name: caddy
    build:
      context: caddy/
      dockerfile: Dockerfile
      target: production
    env_file:
      - .env
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - caddy_data:/data
      - caddy_config:/config

  db:
    container_name: db
    build:
      context: postgresql/
      args:
        - DATASTORE_READONLY_PASSWORD=${DATASTORE_READONLY_PASSWORD}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    environment:
      - DATASTORE_READONLY_PASSWORD=${DATASTORE_READONLY_PASSWORD}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - PGDATA=/var/lib/postgresql/data/db
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  solr:
    container_name: solr
    image: solr:8.11.1
    env_file:
      - .env
    environment:
      - CKAN_CORE_NAME=ckan
      - CKAN_VERSION=2.9
    volumes:
      - solr_data:/var/solr
      - ${PWD}/solr8/ckan_init_solr.sh:/docker-entrypoint-initdb.d/ckan_init_solr.sh

  redis:
    container_name: redis
    image: redis:alpine

volumes:
  ckan_storage:
  pg_data:
  solr_data:
  caddy_data:
    external: true
  caddy_config:
