version: "3.8"

services:
  ckan:
    build:
      dockerfile: ckan/Dockerfile.dev
    platform: linux/x86_64 # Necessary to force docker to pull the amd64 image for running on Mac Silicon
    volumes:
      - ./src:/srv/app/src_extensions

  caddy:
    volumes:
      - ./caddy/Caddyfile.dev:/etc/caddy/Caddyfile

  db:
    env_file:
      - .env

  solr:
    ports:
      - "8983:8983"

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:6.9
    restart: always
    ports:
      - "5050:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=email@example.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  pgadmin-data:
