version: "3"

services:

  ckan:
    container_name: ckan
    image: 848094190915.dkr.ecr.us-east-1.amazonaws.com/ckan:latest
    # TODO make this better - env_file is not officially recommended
    env_file:
      - .env
    links:
      - db
      - solr
      - redis
      - datapusher
    ports:
      - "0.0.0.0:${CKAN_PORT}:5000"
    volumes:
      - ckan_storage:/var/lib/ckan

  datapusher:
    container_name: datapusher
    image: 848094190915.dkr.ecr.us-east-1.amazonaws.com/datapusher:latest
    ports:
      - "8800:8800"

  db:
    container_name: db
    image: 848094190915.dkr.ecr.us-east-1.amazonaws.com/db:latest
    environment:
      - DATASTORE_READONLY_PASSWORD=${DATASTORE_READONLY_PASSWORD}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - PGDATA=/var/lib/postgresql/data/db
    volumes:
      - pg_data:/var/lib/postgresql/data

  solr:
    container_name: solr
    image: 848094190915.dkr.ecr.us-east-1.amazonaws.com/solr:latest
    volumes:
      - solr_data:/opt/solr/server/solr/ckan/data/index

  redis:
    container_name: redis
    image: redis:alpine

volumes:
  ckan_storage: null
  pg_data: null
  solr_data: null
