version: "3.8"

services:
  ckan:
    build:
      dockerfile: Dockerfile.dev
    volumes:
      - ./src:/srv/app/src_extensions

  caddy:
    volumes:
      - ./caddy/Caddyfile.dev:/etc/caddy/Caddyfile

  db:
    env_file:
      - .env
      
  solr:
    ports:
      - "8983:8983"
