name: Staging deploy

on: 
  # Trigger workflow manually via API request or Github UI
  workflow_dispatch:

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
        with:
          path: main
      
      - name: Checkout private tools
        uses: actions/checkout@v2
        with:
          repository: climatesubak/subak-secrets
          token: ${{ secrets.GH_PAT }} # `GH_PAT` is a secret that contains your PAT
          path: secrets

      - name: Decrypt secrets and copy .env
        run: |
          cd secrets
          git-crypt unlock ${{ secrets.GIT_CRYPT_KEY }}
          cp secrets/subakdc/staging/.env main/.env

      - name: Test print
        run: |
          ls -la main
          cat main/.env

      # - name: copy files via ssh 
      #   uses: appleboy/scp-action@master
      #   with:
      #     host: ${{ secrets.SSH_HOST }}
      #     port: ${{ secrets.SSH_PORT }}
      #     username: ${{ secrets.SSH_USERNAME }}
      #     key: ${{ secrets.SSH_KEY }}
      #     passphrase: ${{ secrets.SSH_PASSPHRASE }}
      #     source: "main/*"
      #     target: "docker-ckan"
        
      # - name: Run restart script via ssh
      #   uses: appleboy/ssh-action@master
      #   with:
      #     host: ${{ secrets.SSH_HOST }}
      #     port: ${{ secrets.SSH_PORT }}
      #     username: ${{ secrets.SSH_USERNAME }}
      #     key: ${{ secrets.SSH_KEY }}
      #     passphrase: ${{ secrets.SSH_PASSPHRASE }}
      #     script: |
      #       cd ./docker-ckan
      #       make rebuild.ckan