name: Build and publish all docker-ckan Images
on: 
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build ckan-base 2.7
        uses: docker/build-push-action@v2
        with:
          context: ckan-base/2.7/
          push: true
          tags: openknowledge/ckan-base:2.7
      -
        name: Build ckan-base 2.8
        uses: docker/build-push-action@v2
        with:
          context: ckan-base/2.8/
          push: true
          tags: openknowledge/ckan-base:2.8
      -
        name: Build ckan-base 2.9
        uses: docker/build-push-action@v2
        with:
          context: ckan-base/2.9/
          push: true
          tags: openknowledge/ckan-base:2.9
      -
        name: Build ckan-base 2.9-py2
        uses: docker/build-push-action@v2
        with:
          context: ckan-base/2.9/
          file: Dockerfile.py2
          push: true
          tags: openknowledge/ckan-base:2.9-py2
      -
        name: Build ckan-dev 2.7
        uses: docker/build-push-action@v2
        with:
          context: ckan-dev/2.7/
          push: true
          tags: openknowledge/ckan-dev:2.7
      -
        name: Build ckan-dev 2.8
        uses: docker/build-push-action@v2
        with:
          context: ckan-dev/2.8/
          push: true
          tags: openknowledge/ckan-dev:2.8
      -
        name: Build ckan-dev 2.9
        uses: docker/build-push-action@v2
        with:
          context: ckan-dev/2.9/
          push: true
          tags: openknowledge/ckan-dev:2.9
      -
        name: Build ckan-dev 2.9-py2
        uses: docker/build-push-action@v2
        with:
          context: ckan-dev/2.9/
          file: Dockerfile.py2
          push: true
          tags: openknowledge/ckan-dev:2.9-py2